# Site settings
title: Porooshani.com
email: Porooshani@gmail.com
description: "This is my website, get used to it!"
baseurl: ""
url: "http://poroosh.com"

# Build settings
markdown: kramdown
permalink: pretty
